Homework21: Ekaterina Zavadskaya
KateZavadskaya/mypy2024 pull request #10
Opened 2024-06-27 10:22 UTC by KateZavadskaya

Add done hm12

Docs: hm12_1.py, hm12_2.py

2024-06-27 10:27 UTC, KateZavadskaya commented
@Stml89 Pylint faild becouse of hm11, + local I do not have this error.
Please, check my hm.

2024-06-27 19:59 UTC, Stml89 requested changes

2024-06-27 19:59 UTC, Stml89 commented on hm12_1.py
> +    def __init__(self):
I cannot find "Jokers"

2024-07-15 09:55 UTC, KateZavadskaya commented
Create fixes:
- delete extra files with hm11
- fix comment about Jokers
- was fail with ruff file. Fix it local in ruff.yaml, create commit and push in main.
- create commit and push with hm12
Actions is done.

Please, check it.

2024-07-16 19:38 UTC, Stml89 approved these changes

2024-07-17 17:59 UTC, merged