Homework14: Ekaterina Zavadskaya
KateZavadskaya/mypy2024 pull request #9
Opened 2024-06-25 09:18 UTC by KateZavadskaya

Add hm14

hm14_1.py - done
hm14_2.py - done as comment and via eval 

Docs: hm14_1.py, hm14_2.py

2024-06-25 09:33 UTC, KateZavadskaya commented
@Stml89 local Pylint is ok 💆‍♀️
Please, take a look.

hm14_2.py master Yoda, I'm exhausted( Done via eval😞 and as comment becouse of Linters..

2024-06-29 19:43 UTC, Stml89 commented
Why are files from HW11 present in HW14?

2024-06-29 19:45 UTC, Stml89 requested changes

2024-06-29 19:45 UTC, Stml89 commented on hm14_2.py
how should I rate this task?

2024-06-30 13:09 UTC, KateZavadskaya commented on hm14_2.py
HM has 2 tasks. 1 done, 2 done not according to the rules. So, it seems as 50% from hm 🫠.
Files from HW11 really exist in HM14🙈 Can you, please, make advice, have it is better to delete? Should I close this pull request and create new one?

2024-07-02 09:19 UTC, KateZavadskaya commented on hm14_2.py
Delete local files, create new commit, push.
Pylint have already discussed, Ruff - my side is ok.
Please, check and correct my actions if I am wrong.

2024-07-02 19:21 UTC, Stml89 commented on hm14_2.py
Using `ruff check .` command instead of `ruff --output-format=github .` to fix the Ruff issue

2024-07-02 19:25 UTC, Stml89 commented on hm14_2.py
> HM has 2 tasks. 1 done, 2 done not according to the rules. So, it seems as 50% from hm 🫠. Files from HW11 really exist in HM14🙈 Can you, please, make advice, have it is better to delete? Should I close this pull request and create new one?

In my world, there are only 2 possible cases: 
1\ task is done
2\ task is not done


Based on this, I can say that 2nd task was not done according to the requirements

2024-07-02 19:25 UTC, Stml89 commented on hm14_1.py
Let's give the module (file) better names next time.

2024-07-02 19:26 UTC, Stml89 commented
Pylint hightailed 2 issues:
```
hm14_1.py:44:48: E0606: Possibly using variable 'avagare_1' before assignment (possibly-used-before-assignment)
hm14_1.py:45:49: E0601: Using variable 'avagare_2' before assignment (used-before-assignment)
```

2024-07-02 20:09 UTC, Stml89 approved these changes
Approved 1 task out of 2

2024-07-15 11:58 UTC, merged